version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=local
      - POSTGRES_DB=app
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=local
      - POSTGRES_DB=app
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
      
volumes:
  pgdbdata: null