# Generated by Django 4.2.7 on 2023-11-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='code',
            new_name='token',
        ),
    ]
