# Generated by Django 4.2.7 on 2023-11-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_rename_code_token_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authcode',
            table='auth_codes',
        ),
        migrations.AlterModelTable(
            name='devicetoken',
            table='device_tokens',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
