# Generated by Django 4.2.7 on 2023-12-05 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_devices_user_alter_equipment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0004_alter_authcode_table_alter_devicetoken_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthCode',
            new_name='AuthCodes',
        ),
        migrations.RenameModel(
            old_name='DeviceToken',
            new_name='DeviceTokens',
        ),
    ]
