# Generated by Django 4.2.7 on 2023-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_rename_authcode_authcodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodes',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
