# Generated by Django 4.2.7 on 2023-12-05 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_authcodes_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodes',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 16, 26, 25, 85239)),
        ),
    ]
