# Generated by Django 4.2.7 on 2023-12-05 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_authcodes_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodes',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 17, 23, 22, 19955)),
        ),
        migrations.AlterField(
            model_name='devicetokens',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
