# Generated by Django 4.2.7 on 2023-12-06 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_authcodes_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodes',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 13, 29, 29, 580533)),
        ),
    ]
