# Generated by Django 4.2.7 on 2023-12-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_alter_authcodes_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodes',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
