# Generated by Django 4.2.7 on 2023-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_devices_user_alter_equipment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(default='NoName', max_length=100),
        ),
    ]
