# Generated by Django 4.2.7 on 2023-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_devices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='NoName', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='equipment_type',
            field=models.CharField(default='NoType', max_length=100),
        ),
    ]
