# Generated by Django 4.2.7 on 2023-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_devices_add_date_alter_devices_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='equipment_type',
            field=models.CharField(default='Gague', max_length=100),
        ),
    ]
