# Generated by Django 4.2.7 on 2023-12-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_indicators_equipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicators',
            old_name='equipment_type',
            new_name='indicator_type',
        ),
    ]
